# Completed for PS2
# file: makefile
#
# This is the makefile for this assignment
#
# Programmer: Matt Bundas bundasma@msu.edu
#
# Revision history:
#    02-26-2019 started and finished
#
# Notes:
# use make milne, make simpsons, make gsl, make run

#make commands for our run script
run: run.cpp
	g++ -o run run.cpp -lgsl -lgslcblas -lm

#make commands for milne
milne: milne.cpp
	g++ -o milne milne.cpp

#make commands for simpsons
simpsons: simpsons.cpp
	g++ -o simpsons simpsons.cpp
	
#make commands for gsl
gsl: gsl.cpp
	g++ -o gsl gsl.cpp -lgsl -lgslcblas -lm
